[metadata]
name = gryfsmartio
version = 0.1.5
author = @karlowiczpl
author_email = kkarlowicz@gryfsmart.pl
description = Library for the GryfSmart system
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/karlowiczpl/gryfsmartio
license = MIT
classifiers =
    Programming Language :: Python :: 3
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.8
install_requires =
    pyserial-asyncio==0.6
